# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test NGSF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11, 3.12, 3.13, 3.14]
    steps:
    - name: Checkout branch being tested
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install --upgrade pip setuptools wheel
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache supyfit_bank.zip
      id: zip-cache
      uses: actions/cache@v4
      with:
        path: ./bank
        key: supyfit_bank-static
    - name: Download and extract supyfit_bank.zip
      if: steps.zip-cache.outputs.cache-hit != 'true'
      run: |
        curl -L -H "Content-Type: application/json" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" -o ./supyfit_bank.zip "https://www.wiserep.org/sites/default/files/supyfit_bank.zip"
        unzip -q supyfit_bank.zip
        rm supyfit_bank.zip
    - name: pip cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-2-${{ hashFiles('**/setup.py', '**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-2-
    - name: Install dependencies
      run: |
        python -m pip install pytest pytest-cov flake8
        python -m pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude docs
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude docs,versioneer.py,NGSF/_version.py,NGSF/tests,NGSF/*/__init__.py
    - name: Test with pytest
      run: |
        pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
